FROM openjdk:17-jdk-slim

WORKDIR /app

RUN apt-get update && apt-get install -y wget \
    && wget https://services.gradle.org/distributions/gradle-7.4-bin.zip \
    && unzip gradle-7.4-bin.zip \
    && mv gradle-7.4 /opt/gradle \
    && ln -s /opt/gradle/bin/gradle /usr/bin/gradle

COPY gradle /app/gradle
COPY build.gradle settings.gradle /app/
RUN gradle build --no-daemon

COPY src /app/src

RUN gradle bootJar --no-daemon

EXPOSE 8080

CMD ["java", "-jar", "build/libs/my-app.jar"]
